### ISSUE TITLE
Xamarin.macOS SDK not found

### ISSUE THREAD

**Issue by mfkl** [actions/runner-images#6375]
### Description

Hi there,

5 days ago, the build of my cross-platform .NET library started failing on the Windows agent for the macOS target, with no changes on my part. https://videolan.visualstudio.com/LibVLCSharp/_build?definitionId=22

The macOS Xamarin SDK is suddenly not found anymore
```
error CS0246: The type or namespace name 'AppKit' could not be found
error CS0246: The type or namespace name 'NSView' could not be found
```

- No changes on my part. It started failing on October 5th.
- `dotnet workload install macos` is still running successfully.
- Same code and script still build fine on `macOS-10.15` but the `windows-2022` no longer builds and I can't find out why.
- I have checked the recent commit history but nothing catches my eye when it comes to the Xamarin.Mac SDK on the Windows microsoft Azure Pipeline agents.
- I cannot reproduce locally on my Win10 desktop machine.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Agent name: 'Azure Pipelines 4'
Agent machine name: 'WIN-RVFKUT6DD8L'
Current agent version: '2.210.1'
Operating System
Microsoft Windows Server 2022
10.0.20348
Datacenter
Runner Image
Image: windows-2022
Version: 20221002.2
Included Software: https://github.com/actions/runner-images/blob/win22/20221002.2/images/win/Windows2022-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20221002.2
Runner Image Provisioner
1.0.0.0-main-20220916-1
Current image version: '20221002.2'

https://videolan.visualstudio.com/LibVLCSharp/_build/results?buildId=6154&view=logs&s=6884a131-87da-5381-61f3-d7acc3b91d76&j=0bc77094-9fcd-5c38-f6e4-27d2ae131589

### Is it regression?

yes. The following image could still build fineRunner Image Image: windows-2022 Version: 20220925.1 Included Software: https://github.com/actions/runner-images/blob/win22/20220925.1/images/win/Windows2022-Readme.md Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20220925.1 Runner Image Provisioner 1.0.0.0-main-20220916-1 Current image version: '20220925.1'

### Expected behavior

Xamarin.Mac SDK is found on Windows Azure agents.

### Actual behavior

Xamarin.Mac SDK is not found on Windows Azure agents.

### Repro steps

- Fork https://github.com/videolan/libvlcsharp/tree/3.x/buildsystem
- run the Windows build on your own pipeline

**Comment by igorboskovic3** [comment]
Hi @mfkl, we will take a look, thanks for reporting this one.

**Comment by mfkl** [comment]
Reproduced on Github Action agents as well.

**Comment by igorboskovic3** [comment]
Hi @mfkl and thank you, Ive already created testing environment, but till now I didnt find anything unusual form our side, so ive pinged Xamarin team and waiting for response

**Comment by al-cheb** [comment]
@mfkl , it's a bug in VS 2022 - https://developercommunity.visualstudio.com/t/XamarinMac-binaries-are-missing-in-173/10164443#T-ND10165277

As workaround update `mac-test-ci.csproj` file:
```
<Project Sdk="MSBuild.Sdk.Extras">
  <PropertyGroup>
    <TargetFrameworks>Xamarin.Mac20;net6.0-macos</TargetFrameworks>
    <RootNamespace>mac_test_ci</RootNamespace>
  </PropertyGroup>
	<ItemGroup Condition=" $(TargetFramework.StartsWith('Xamarin.Mac')) ">
    <Reference Include="Xamarin.Mac">
      <HintPath Condition="Exists('c:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\Xamarin.VisualStudio')">C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\Xamarin.VisualStudio\Xamarin.Mac.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>
```

![image](https://user-images.githubusercontent.com/47745270/198991623-eb57728e-51c7-4d8d-8e85-ca67f8259769.png)

**Comment by mfkl** [comment]
Ok, thank you for the link and workaround!
