### ISSUE TITLE
Error: redefinition of module 'SwiftBridging' 

### ISSUE THREAD

**Issue by QiZhan** [actions/runner-images#9577]
### Description

Build works fine with the default Xcode 15.0.1. However when we select Xcode 15.2, builds fail with Error: redefinition of module 'SwiftBridging'.

Possible useful link: https://forums.developer.apple.com/forums/thread/739510

### Platforms affected

- [ ] Azure DevOps
- [ ] GitHub Actions - Standard Runners
- [X] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [X] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

macos-13-xlarge

### Is it regression?

N/A

### Expected behavior

Build should pass with Xcode 15.2

### Actual behavior

Github Actions return build error: /Applications/Xcode_15.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/swift/module.modulemap,line=13,col=8::redefinition of module 'SwiftBridging'

### Repro steps

1.  Select Xcode version by updating "sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer" in Github workflows
2. Build on macos-13-xlarge runner.

**Comment by sergei-pyshnoi** [comment]
Hello @QiZhan.  Can you please provide simple repro step? Its can be sample xcode project with action yaml.

**Comment by QiZhan** [comment]
Hi [sergei-pyshnoi](https://github.com/sergei-pyshnoi), The only change we made was selecting Xcode 15.2 in the job compared with the working job with Xcode 15.0.1. We archive using bundle exec fastlane gym and our project is using React Native.

**Comment by sergei-pyshnoi** [comment]
> Hi [sergei-pyshnoi](https://github.com/sergei-pyshnoi), The only change we made was selecting Xcode 15.2 in the job compared with the working one with Xcode 15.0.1. Not sure if this info will help, we archive using bundle exec fastlane gym and our project is using React Native.

Unfortunately without any additional information we cannot start any investigation. I mean for example its error can be your project related. At least changing Xcode for building its kind of major changing and its It's not uncommon for this to cause errors during the build process.

**Comment by erik-bershel** [comment]
Hey @QiZhan!
I'm going to close this item since no repro steps were provided. Feel free to reopen it in case you got some information to investigate.

**Comment by ruslanskorb** [comment]
Hey, @erik-bershel.

I have a [project](https://github.com/ruslanskorb/RSKImageCropper/tree/develop) for you where this error occurs.

[Failed job logs.zip](https://github.com/actions/runner-images/files/14890964/logs_22479285857.zip)

Let me know if there is anything else I can do to help resolve this issue.

**Comment by matbouil** [comment]
Hi,

**Comment by MaksimZhukov** [comment]
Hello @matbouil!
Unfortunately, we have not found the root cause yet. 
It would be great for further investigation if you could also provide a link to the public repository where the issue occurred.

**Comment by matbouil** [comment]
> Hello @matbouil! Unfortunately, we have not found the root cause yet. It would be great for further investigation if you could also provide a link to the public repository where the issue occurred.

Hi Maksim,
Unfortunately, my project is not on a public repository and can't share it with you.
However, as @ruslanskorb said, the build works perfectly using Xcode 15.0.1.

**Comment by nanduu058** [comment]
Adding our observation here - 
Last successful build with Xcode 15.2 was on Feb 12 and we noticed that it started failing from Feb 23.

In between, we noticed that the macOS 13 image got updated. We are thinking this could be a possible root cause. 

**Mac OS image on feb 12** 
Image: macos-13
Version: 20240114.1

**Mac OS image we noticed on Feb 23**
Image: macos-13
Version: 20240219.1

You may try to look into this direction and see if you can find any root cause.

**Comment by MaksimZhukov** [comment]
Hello @nanduu058!
Thank you for providing additional information! 
Could you please share the link to the latest successful build with Xcode 15.2?

**Comment by nanduu058** [comment]
@MaksimZhukov 
Unfortunately, due to security concerns we cant share our project or logs. Is there any office hours for your clients to jump on a call to debug any of this kinds of issues? We can do a screen share

**Comment by nanduu058** [comment]
@MaksimZhukov Do you have any update on this?

**Comment by matbouil** [comment]
Hello @MaksimZhukov 
We would also be interested in an update on this subject too ;-)

**Comment by MaksimZhukov** [comment]
Hello everyone!
The issue is caused by installing multiple versions of Xcode alongside and can be fixed by deleting Xcode.app:
```yml
- name: Delete Xcode.app
  run: sudo rm -rf /Applications/Xcode.app
```
Here is a link to the [successful run](https://github.com/MaksimZhukov/RSKImageCropper/actions/runs/8875692905/job/24365659905) and corresponding [workflow file](https://github.com/MaksimZhukov/RSKImageCropper/actions/runs/8875692905/workflow).

I'm closing the issue. Feel free to contact us if you have any questions or concerns.

**Comment by nanduu058** [comment]
https://github.com/actions/runner-images/issues/9542#issuecomment-2073287239

We were able to pass our build from the above mentioned link. However, we are curious if it can be fixed from GitHub side as this one stated happening with the recent update. It would be really difficult to triage this kind of issues that came up with the updates as it is difficult to reproduce locally.
