### ISSUE TITLE
Homebrew LLVM 19/20/21 broken on latest MacOS 15 image

### ISSUE THREAD

**Issue by tcbrindle** [actions/runner-images#13036]
### Description

Trying to compile a C++ program using clang++ installed via `brew install llvm@20` gives:

```
In file included from /opt/homebrew/opt/llvm@20/bin/../include/c++/v1/optional:1296:
In file included from /opt/homebrew/opt/llvm@20/bin/../include/c++/v1/atomic:607:
In file included from /opt/homebrew/opt/llvm@20/bin/../include/c++/v1/__atomic/atomic_flag.h:19:
In file included from /opt/homebrew/opt/llvm@20/bin/../include/c++/v1/__thread/support.h:112:
/opt/homebrew/opt/llvm@20/bin/../include/c++/v1/__thread/support/pthread.h:18:10: error: 'pthread.h' file not found with <angled> include; use "quotes" instead
/opt/homebrew/opt/llvm@20/bin/../include/c++/v1/__thread/support/pthread.h:19:10: fatal error: 'sched.h' file not found
```

[Full log](https://github.com/tcbrindle/pointer/actions/runs/17808696319/job/50626956669)

The same happens with `llvm@19` and `llvm@21`.

### Platforms affected

- [ ] Azure DevOps
- [x] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] macOS 15
- [x] macOS 15 Arm64
- [ ] macOS 26 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022
- [ ] Windows Server 2025

### Image version and build link

 Image: macos-15-arm64
 Version: 20250911.2324

Build log: https://github.com/tcbrindle/pointer/actions/runs/17808696319/job/50626956669

### Is it regression?

Yes -- previously working in image 20250830.2281  [successful build log](https://github.com/tcbrindle/pointer/actions/runs/17557743387/job/49866165726)

### Expected behavior

The C++ compiler should be able to find the system headers

### Actual behavior

The compiler is unable to find the system headers and errors out

### Repro steps

* Install LLVM 19/20/21
  `brew install llvm@20`
* Try to compile a C++ program which (eventually) includes any system headers
   `$(brew --prefix llvm@20)/clang++ test_file.cpp`

**Comment by tcbrindle** [comment]
Update: it seems that the problem occurs when trying to use **C++20 modules** with Homebrew LLVM. It looks to be the same bug as https://github.com/Homebrew/homebrew-core/issues/221782

I've updated the issue title and description.

**Comment by v-aartis17** [comment]
Hi @tcbrindle ,

Can you just try with the latest image : `20250916.2338` macOS 15 arm 64 which is available. 
I tried and can see no errors, please see below successful run:

<img width="1453" height="675" alt="Image" src="https://github.com/user-attachments/assets/c6de1c7e-6030-4b0d-8364-38820a44a65f" />

Please do let me know, if issue is still there, Thank you.

**Comment by tcbrindle** [comment]
Hi @aartis17,

It was successful because I disabled building with C++20 modules :)

I've just re-enabled module builds in a new PR which still shows the error on the latest `20250916.2338` image.  [Pull request](https://github.com/tcbrindle/pointer/pull/6), [Actions log](https://github.com/tcbrindle/pointer/actions/runs/17919757122)

Please use the [reenable_modules_ci](https://github.com/tcbrindle/pointer/tree/reenable_modules_ci) branch to see the error.

**Comment by v-aartis17** [comment]
Hi @tcbrindle ,

The error is due to the compiler is missing system headers `pthread.h`, `sched.h` 

When using Homebrew-installed versions of LLVM (like llvm@20), the compiler  does not automatically use the macOS system SDK path.
Hence, I have slightly modified the code to pass the correct SDK path to the compiler using the `-isysroot` flag

Please find modified code:

```
 - name: Configure
      run: |
       echo "Setting up SDKROOT manually"
       export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
       cmake -B build -GNinja \
          -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
          -DCMAKE_CXX_COMPILER=${{matrix.cxx}} \
          -DCMAKE_EXE_LINKER_FLAGS="${{matrix.ldflags}} -isysroot $SDKROOT" \
          -DCMAKE_CXX_FLAGS="-isysroot $SDKROOT" \
          -DCMAKE_CXX_EXTENSIONS=Off \
          -DCMAKE_COMPILE_WARNING_AS_ERROR=On \
          -DCMAKE_LINK_WARNING_AS_ERROR=On \
          -DTCB_POINTER_BUILD_MODULE=${{matrix.build_module}}
```

Also, I have added the job which checks the exact macOS SDK path:

```
 - name: Show macOS SDK path
      run: xcrun --sdk macosx --show-sdk-path
```

Please find screenshot of successful run after above modification:


<img width="1453" height="675" alt="Image" src="https://github.com/user-attachments/assets/ee5bbdfd-a5a5-4ee6-855e-1b077fe0c805" />

**Comment by erik-bershel** [comment]
Hey @tcbrindle! 👋 

The bug is external to us, just like it is to Homebrew, as it comes from upstream. We can't implement the proposed workaround because there's a risk of breaking a significant number of users who already configure their environments differently or use `clang` from another source, which is quite possible on macOS.
In this regard, I am forced to close the request, but please feel free to ask questions or offer additional arguments if you have any - I will be happy to answer.
