### ISSUE TITLE
ubuntu-22.04 breaks compilation to static executables with GHC 9.4

### ISSUE THREAD

**Issue by andreasabel** [actions/runner-images#6689]
### Description

Building statically linked executables with GHC 9.4 fails under `ubuntu-22.04` with a linker error ("undefined reference to '__xmknod'"), when the same workflow succeeds under `ubuntu-20.04`.

`xmknod` seems to be the POSIX function described here: http://refspecs.linux-foundation.org/LSB_4.0.0/LSB-Core-generic/LSB-Core-generic/baselib---xmknod-1.html

It could be that some library is lacking on `ubuntu-22.04` that GHC 9.4 (shipped with `ubuntu-22.04`) expects.

(NB. As a consequence, workflows using `ubuntu-latest` get broken.)

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

https://github.com/andreasabel/ci-executable-static/actions/runs/3620850873/jobs/6103575852
Image: ubuntu-22.04
  Version: 20221127.1

### Is it regression?

Yes, works with ubuntu-20.04.

### Expected behavior

Build a static executable with GHC 9.4.

### Actual behavior

Linking fails with error:
```
/usr/local/.ghcup/ghc/9.4.3/lib/ghc-9.4.3/lib/../lib/x86_64-linux-ghc-9.4.3/unix-2.7.3/libHSunix-2.7.3.a(Files.o):
function ghczuwrapperZC1ZCunixzm2zi7zi3ZCSystemziPosixziFilesZCmknod: 
error: undefined reference to '__xmknod'
```
https://github.com/andreasabel/ci-executable-static/actions/runs/3620850873/jobs/6103575852#step:4:38

### Repro steps

I prepared a MWE, please checkout the workflow at https://github.com/andreasabel/ci-executable-static/blob/master/.github/workflows/build.yml.
The important bit is the `--enable-executable-static` flag in the build command:
```
cabal build all --enable-executable-static  --enable-split-sections
```

**Comment by mikhailkoliada** [comment]
@hasufell Hey Julian! Any ideas on the above? ^^

**Comment by hasufell** [comment]
I'm not sure why you expect static linking with glibc to work out of the box. It's not trivial. Use an alpine docker image if you want static linking. GHCup supports alpine.

**Comment by mikhailkoliada** [comment]
@andreasabel I am generally agree with what @hasufell said. `__xmknod` comes from glibc and is responsible for `mknod()` as far as I remember. Given, that we do not provide any statically build toolchain, it is not what we can help you with. Apart from that, your build may require statically build libstdc++ and libgpm which we also do not provide in stock.

For now I am going to close the ticket, but feel free to reopen it or ping us again if you have questions left.
