### ISSUE TITLE
Unresolved external symbols in C++ stdlib with runner image 20221120.1

### ISSUE THREAD

**Issue by adamreeve** [actions/runner-images#6629]
### Description

Our builds have started failing after the Windows runner image was upgraded to version 20221120.1, with errors due to missing symbols from the C++ standard library, eg `__std_max_element_1` and  `__std_min_element_8`.

This looks to be related to Visual Studio being upgraded from 17.3.32929.385 to 17.4.33110.190 and appears to be very similar to issue #6091 which was caused by Visual Studio being upgraded previously.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Version 20221120.1

Build log: https://github.com/G-Research/ParquetSharp/actions/runs/3536673497/jobs/5935934107

### Is it regression?

Yes, previous good build with image 20221027.1: https://github.com/G-Research/ParquetSharp/actions/runs/3528174395/jobs/5917991598

### Expected behavior

Build completes successfully and can resolve C++ standard library symbols.

### Actual behavior

Linker errors due to unresolved symbols in the C++ standard library:
```
(Link target) -> 
  arrow.lib(type.cc.obj) : error LNK2019: unresolved external symbol __std_max_element_1 referenced in function "signed char const * __cdecl std::_Max_element_unchecked<signed char const *,struct std::less<void> >(signed char const *,signed char const *,struct std::less<void>)" (??$_Max_element_unchecked@PEBCU?$less@X@std@@@std@@YAPEBCPEBC0U?$less@X@0@@Z) [D:\a\ParquetSharp\ParquetSharp\build\x64-windows-static\cpp\ParquetSharpNative.vcxproj]
  arrow.lib(scalar_if_else.cc.obj) : error LNK2019: unresolved external symbol __std_min_element_8 referenced in function "public: static __int64 __cdecl arrow::internal::Bitmap::VisitWords<3,class <lambda_1e6d42145416e081fb4ab9cdf7f4fca2>,unsigned __int64>(class arrow::internal::Bitmap const (&)[3],class <lambda_1e6d42145416e081fb4ab9cdf7f4fca2> &&)" (??$VisitWords@$02V<lambda_1e6d42145416e081fb4ab9cdf7f4fca2>@@_K@Bitmap@internal@arrow@@SA_JAEAY02$$CBV012@$$QEAV<lambda_1e6d42145416e081fb4ab9cdf7f4fca2>@@@Z) [D:\a\ParquetSharp\ParquetSharp\build\x64-windows-static\cpp\ParquetSharpNative.vcxproj]
  arrow.lib(aggregate_quantile.cc.obj) : error LNK2001: unresolved external symbol __std_min_element_8 [D:\a\ParquetSharp\ParquetSharp\build\x64-windows-static\cpp\ParquetSharpNative.vcxproj]
  arrow.lib(scalar_if_else.cc.obj) : error LNK2019: unresolved external symbol __std_max_element_8 referenced in function "public: static __int64 __cdecl arrow::internal::Bitmap::VisitWords<3,class <lambda_1e6d42145416e081fb4ab9cdf7f4fca2>,unsigned __int64>(class arrow::internal::Bitmap const (&)[3],class <lambda_1e6d42145416e081fb4ab9cdf7f4fca2> &&)" (??$VisitWords@$02V<lambda_1e6d42145416e081fb4ab9cdf7f4fca2>@@_K@Bitmap@internal@arrow@@SA_JAEAY02$$CBV012@$$QEAV<lambda_1e6d42145416e081fb4ab9cdf7f4fca2>@@@Z) [D:\a\ParquetSharp\ParquetSharp\build\x64-windows-static\cpp\ParquetSharpNative.vcxproj]
  arrow.lib(aggregate_quantile.cc.obj) : error LNK2019: unresolved external symbol __std_min_element_2 referenced in function "short * __cdecl std::_Min_element_unchecked<short *,struct std::less<void> >(short *,short *,struct std::less<void>)" (??$_Min_element_unchecked@PEAFU?$less@X@std@@@std@@YAPEAFPEAF0U?$less@X@0@@Z) [D:\a\ParquetSharp\ParquetSharp\build\x64-windows-static\cpp\ParquetSharpNative.vcxproj]
  arrow.lib(aggregate_quantile.cc.obj) : error LNK2019: unresolved external symbol __std_min_element_4 referenced in function "int * __cdecl std::_Min_element_unchecked<int *,struct std::less<void> >(int *,int *,struct std::less<void>)" (??$_Min_element_unchecked@PEAHU?$less@X@std@@@std@@YAPEAHPEAH0U?$less@X@0@@Z) [D:\a\ParquetSharp\ParquetSharp\build\x64-windows-static\cpp\ParquetSharpNative.vcxproj]
  D:\a\ParquetSharp\ParquetSharp\bin\x64-windows-static\ParquetSharpNative.dll : fatal error LNK1120: 5 unresolved externals [D:\a\ParquetSharp\ParquetSharp\build\x64-windows-static\cpp\ParquetSharpNative.vcxproj]
```

### Repro steps

I haven't tried to make a minimal reproducible example as I'm hoping this is trivial to fix by using the same fix as for #6091 (and hopefully putting some process in place to stop this happening again the next time Visual Studio is upgraded?), but if needed I can try to come up with a smaller example. The failures are reproduced consistently with the builds in https://github.com/G-Research/ParquetSharp though. I also tested without using cached vcpkg dependencies to verify the problem wasn't caused by using incompatible cached build artifacts.

**Comment by mikhailkoliada** [comment]
@adamreeve have you tried to update vc components in runtime as mentioned in the original ticket you referenced? AFAIR, there is a new release.

**Comment by adamreeve** [comment]
Hi @mikhailkoliada, good point, I tried that now and it does fix the issue. I added the following step to remove the old VC component which was suggested in the linked ticket:
```
    - name: Workaround test
      if: runner.os == 'Windows'
      run: |
        Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
        $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
        $componentsToRemove= @(
          "Microsoft.VisualStudio.Component.VC.14.33.17.3.ARM"
          "Microsoft.VisualStudio.Component.VC.14.33.17.3.ARM.Spectre"
          "Microsoft.VisualStudio.Component.VC.14.33.17.3.ARM64"
          "Microsoft.VisualStudio.Component.VC.14.33.17.3.ARM64.Spectre"
          "Microsoft.VisualStudio.Component.VC.14.33.17.3.x86.x64"
          "Microsoft.VisualStudio.Component.VC.14.33.17.3.x86.x64.Spectre"
          "Microsoft.VisualStudio.Component.VC.14.33.17.3.ATL"
          "Microsoft.VisualStudio.Component.VC.14.33.17.3.ATL.Spectre"
          "Microsoft.VisualStudio.Component.VC.14.33.17.3.ATL.ARM"
          "Microsoft.VisualStudio.Component.VC.14.33.17.3.ATL.ARM.Spectre"
          "Microsoft.VisualStudio.Component.VC.14.33.17.3.ATL.ARM64"
          "Microsoft.VisualStudio.Component.VC.14.33.17.3.ATL.ARM64.Spectre"
          "Microsoft.VisualStudio.Component.VC.14.33.17.3.MFC"
          "Microsoft.VisualStudio.Component.VC.14.33.17.3.MFC.Spectre"
          "Microsoft.VisualStudio.Component.VC.14.33.17.3.MFC.ARM"
          "Microsoft.VisualStudio.Component.VC.14.33.17.3.MFC.ARM.Spectre"
          "Microsoft.VisualStudio.Component.VC.14.33.17.3.MFC.ARM64"
          "Microsoft.VisualStudio.Component.VC.14.33.17.3.MFC.ARM64.Spectre"
        )
        [string]$workloadArgs = $componentsToRemove | ForEach-Object {" --remove " +  $_}
        $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
        # should be run twice
        $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
        $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
```
The successful build can be seen here: https://github.com/G-Research/ParquetSharp/actions/runs/3543794755/jobs/5950543285

**Comment by mikhailkoliada** [comment]
Will be deployed next week

**Comment by mikhailkoliada** [comment]
Deployed
