### ISSUE TITLE
Error: redefinition of module 'SwiftBridging' 

### ISSUE THREAD

**Issue by hdesai-dave** [actions/runner-images#9542]
### Description

Using macos-13 runners which have xcode 15.0.1 as default xcversion, when we use xcversion 15.1 the builds fail with Error: redefinition of module 'SwiftBridging'
Have also tried moacos-14 but same issue exists on it.
Works fine on default 15.0.1 xcversion only.

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] macOS 11
- [ ] macOS 12
- [X] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

20240219.1

### Is it regression?

not sure

### Expected behavior

Build should pass with xcversion 15.0.1. 

### Actual behavior

Build fails with Error: redefinition of module 'SwiftBridging' 

### Repro steps

Build a react native iOS app which uses expo modules on non default xcversion 15.1 for example on macos-13 runner.

**Comment by Alexey-Ayupov** [comment]
Hello @hdesai-dave. Quick question, do you select XCode 15.1 before actual deployment? If not you can try this command `sudo xcode-select -s /Applications/Xcode_15.1.app/Contents/Developer` .

Also we need at least minimal repro steps, ideally repository which we can fork and troubleshoot the issue there.

**Comment by sergei-pyshnoi** [comment]
@hdesai-dave . I am closing this issue as stale since we hear nothing from you. Please reach me for reopening if problem still persist.

**Comment by hdesai-dave** [comment]
@sergei-pyshnoi sorry i was out for few days, we use 
`- uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.1.0'`
        
to set xcode version

**Comment by lasha-dave** [comment]
@sergei-pyshnoi Sorry build is passing on Xcode 15.0.1 but failing on Xcode 15.1+. We only see this issue on Github Actions. There are similar issue filed on Apple forums, related to multiple Xcodes installed on the same machine.
https://forums.developer.apple.com/forums/thread/739510

**Comment by matbouil** [comment]
Hi,Same issue here.
Any progress on this

**Comment by jrbenny35** [comment]
Ran into this today as well, using the forums link above this was able to fix it:
```
name: Delete Xcode App 
run: sudo rm -rf /Applications/Xcode.app
```
