### ISSUE TITLE
pyodbc 4.0.32 fails to build on Ubuntu 22.04.

### ISSUE THREAD

**Issue by RajJani** [actions/runner-images#6126]
### Description

I am using Azure DevOps build pipeline with agent specification as ubuntu-22.04
My requirements.txt includes pyodbc==4.0.32 (since latest version of [pyodbc 4.0.34 is broken](https://github.com/mkleehammer/pyodbc/issues/1095) as of today)

The build fails with it tries to install pyodbc.

The error reads as 

```
Running setup.py install for pyodbc: started
  Running setup.py install for pyodbc: finished with status 'error'
  error: subprocess-exited-with-error
  
  × Running setup.py install for pyodbc did not run successfully.
  │ exit code: 1
  ╰─> [16 lines of output]
      /home/vsts/work/1/s/worker_venv/lib/python3.9/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'library-dirs' will not be supported in future versions. Please use the underscore name 'library_dirs' instead
        warnings.warn(
      running install
      running build
      running build_ext
      building 'pyodbc' extension
      creating build
      creating build/temp.linux-x86_64-3.9
      creating build/temp.linux-x86_64-3.9/src
      gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DPYODBC_VERSION=4.0.30 -I/home/vsts/work/1/s/worker_venv/include -I/opt/hostedtoolcache/Python/3.9.13/x64/include/python3.9 -c src/buffer.cpp -o build/temp.linux-x86_64-3.9/src/buffer.o -Wno-write-strings
      In file included from src/buffer.cpp:12:
      src/pyodbc.h:56:10: fatal error: sql.h: No such file or directory
         56 | #include <sql.h>
            |          ^~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> pyodbc

note: This is an issue with the package mentioned above, not pip.
```

Look at the attached Screenshot for the error message.
![error](https://user-images.githubusercontent.com/25382999/185950986-45bc0508-53a5-4d84-8299-75adb32d1fd4.JPG)

On digging a little I found this.
https://docs.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver16#ubuntu18

I was able to fix the build issue by adding unixODBC to the ubuntu-22.04 image
I did that by adding sudo apt-get install -y unixodbc-dev in the build extension part of the pipeline.
![Capture](https://user-images.githubusercontent.com/25382999/185952649-e888d14d-8d48-437c-ab3a-d5df19b051f8.JPG)

This resolved the build error and the code deploy was successful.

### Platforms affected

- [X] Azure DevOps
- [ ] GitHub Actions

### Virtual environments affected

- [ ] Ubuntu 18.04
- [ ] Ubuntu 20.04
- [X] Ubuntu 22.04
- [ ] macOS 10.15
- [ ] macOS 11
- [ ] macOS 12
- [ ] Windows Server 2019
- [ ] Windows Server 2022

### Image version and build link

![1](https://user-images.githubusercontent.com/25382999/185953921-3bf04b3c-24ee-4f13-b3ee-a0ca83531d45.JPG)
![2](https://user-images.githubusercontent.com/25382999/185953950-d1dad26b-1b98-402d-b007-839db56386c0.JPG)

### Is it regression?

No

### Expected behavior

ubuntu 22.04 should be able to build pyodbc==4.0.32 successfully

### Actual behavior

It fails to build. The quick and easy way to fix is to add unixODBC

### Repro steps

1. Create a Function app that uses pyodbc(include pyodbc==4.0.32 in the requirements.txt)
2. Use Ubuntu 22.04 as the agent specification
3. Use python 3.9
4. set Script for install application dependencies as
5. `python3.9 -m venv worker_venv
source worker_venv/bin/activate
pip3.9 install setuptools
/home/vsts/work/1/s/worker_venv/bin/python3.9 -m pip install --upgrade pip
pip3.9 install --target="./.python_packages/lib/site-packages" -r ./requirements.txt`
6. Run build.

This should result in build failure.

**Comment by al-cheb** [comment]
Hello @RajJani.
We will try to add sqltools on Ubuntu Server 22.04.

**Comment by miketimofeev** [comment]
@RajJani we will deploy the new image next week, most likely by Tue-Wed.

**Comment by al-cheb** [comment]
The new image with unixodbc-dev has been deployed.

**Comment by rad-pat** [comment]
Can this also be added to Ubuntu 24.04? Fails in same way, unixodbc-dev is missing
