### ISSUE TITLE
Missing atlbase.h file in windows-2022 runner

### ISSUE THREAD

**Issue by kanak-clumio** [actions/runner-images#9873]
### Description

We have a CI pipeline that stopped working from 16hrs ago. It is in a private repository and there is no code change in it for weeks.

This is the error we are getting -
```
fatal error C1083: Cannot open include file: 'atlbase.h': No such file or directory
```

It uses windows-2022 runner

worked yesterday: https://github.com/actions/runner-images/blob/win22/20240421.1/images/windows/Windows2022-Readme.md
broken today: https://github.com/actions/runner-images/blob/win22/20240514.3/images/windows/Windows2022-Readme.md

Since there was no recent changes to our repository there must be some changes to the windows-2022 runner that made altbase.h no longer available when compiling
I see the package name in `win22/20240514.3` is `Microsoft.VisualStudio.Component.VC.ATL` which is different from the previous release.

We also filed an issue with microsoft for this - https://github.com/microsoft/setup-msbuild/issues/127

### Platforms affected

- [ ] Azure DevOps
- [X] GitHub Actions - Standard Runners
- [ ] GitHub Actions - Larger Runners

### Runner images affected

- [ ] Ubuntu 20.04
- [ ] Ubuntu 22.04
- [ ] Ubuntu 24.04
- [ ] macOS 11
- [ ] macOS 12
- [ ] macOS 13
- [ ] macOS 13 Arm64
- [ ] macOS 14
- [ ] macOS 14 Arm64
- [ ] Windows Server 2019
- [X] Windows Server 2022

### Image version and build link

Image: windows-2022
Version: 20240514.3.0
Included Software: https://github.com/actions/runner-images/blob/win22/20240514.3/images/windows/Windows2022-Readme.md
Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20240514.3

### Is it regression?

Yes, it was working in version 20240421.1.0

### Expected behavior

We should not see 'atlbase.h' not found error.

### Actual behavior

Seeing error that 'atlbase.h' file is not found.

### Repro steps

Run a workflow like this and try to build any C++ Visual Studio project which imports this header file - 
```
name: CI
on:
  push:
    branches: [ 'main', 'releases/**' ]
  pull_request:
    branches: [ '**' ]
  workflow_dispatch:
  # Allow manual trigger for debugging the workflow.
jobs:
  CI-checks:
    runs-on: windows-2022
    steps:
      - name: Disable git autocrlf
        run: git config --global core.autocrlf false

      - uses: actions/checkout@v4

      # The msbuild version is dictated by the Windows image provided by GitHub.
      - uses: microsoft/setup-msbuild@v2
      - uses: darenm/Setup-VSTest@v1.2
      - name: Build and test with Sonar Wrapper
        shell: cmd
        run: test-all.cmd

```

**Comment by erik-bershel** [comment]
Hey @kanak-clumio!

Take a look here, please: https://github.com/actions/runner-images/issues/9701
We excluded multiple Visual Studio 2022 VC components from the image due to a bug in VS which blocks other images users. I may recommend you to add necessary components/version in runtime using snippet:

```yml
    steps:
      - name: Delete components
        run: |
                Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
                $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
                $componentsToRemove= @(
                    "Microsoft.VisualStudio.Component.VC.ATL"
                )
                [string]$workloadArgs = $componentsToRemove | ForEach-Object {" --remove " +  $_}
                $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
                # should be run twice
                $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
                $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
      
      - name: Install components
        run: |
                Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
                $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
                $componentsToRemove= @(
                  "Microsoft.VisualStudio.Component.VC.v141.ATL"
                  "Microsoft.VisualStudio.Component.VC.14.29.16.11.ATL"
                )
                [string]$workloadArgs = $componentsToRemove | ForEach-Object {" --add " +  $_}
                $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
                # should be run twice
                $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
                $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden

**Comment by erik-bershel** [comment]
@kanak-clumio
I'll wait for your response. One version of the `ATL` package must contain a header file: 
```text
                  "Microsoft.VisualStudio.Component.VC.v141.ATL"
                  "Microsoft.VisualStudio.Component.VC.14.29.16.11.ATL"
```
I recommend reporting the bug to the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/index.html/report) to understand why it was excluded in the latest version of `Component.VC.ATL`.

**Comment by sodul** [comment]
@erik-bershel uninstalling and re-installing the ATL component seems to fix the compilation issue but it add 5-6m to the runs.
We found that the missing header is actually present on disk at:
```
/c/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.39.33519/atlmfc/include/atlbase.h
```

So we believe that it was just not installed properly and not added to the import paths of the compiler. If there is a faster way to make the existing atlbase.h discoverable that might be good enough.

**Comment by erik-bershel** [comment]
Hey @sodul!

Glad to hear that we localised bug. Appreciate your effort! Would be very nice if you report this bag to the Visual Studio so they can fix it for other users.

Same time I found a discussion on SO: https://stackoverflow.com/questions/3898287/c-include-atlbase-h-is-not-found

There were mentioned two options:
```
After that add additional VC++ directories in the project properties:

Include directories: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.14.26428\atlmfc\include
Library directories: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\VC\Tools\MSVC\14.14.26428\atlmfc\lib\x86
The VC++ compiler should now be able to find the ATL source and library files.
```

```
C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC>mklink /d atlmfc "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\atlmfc"
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\atlmfc\lib>mklink /d amd64 "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.11.25503\atlmfc\lib\x64
```
I am sure that the second one will definitely work if you correct a path.

**Comment by erik-bershel** [comment]
This action might be also a solution of the issue: https://github.com/marketplace/actions/setup-msvc-developer-command-prompt

**Comment by kanak-clumio** [comment]
Thanks @erik-bershel for the help!

I've made a change to add the workaround you suggested of deleting and adding components so that our CI goes through. This increases the build time by 7 min but we can manage it till your above change is available in the next windows-2022 runner version.

**Comment by Metadorius** [comment]
Had the same issue today when we merged another PR in our project. https://github.com/Phobos-developers/Phobos/actions/runs/9141719975/job/25136537634

Is it possible to somehow revert to the previous runner version where it was working?

**Comment by erik-bershel** [comment]
> Is it possible to somehow revert to the previous runner version where it was working?

Nope. Only to wait for the next release or to update ATL library in runtime.

**Comment by provegard** [comment]
Do you plan on making a release with the fix in the next few days? I'm considering if I should add the workaround to our pipeline, but if a new release is in the works, I might as well wait.

**Comment by erik-bershel** [comment]
Hey @provegard!
We are expecting release on the very next week, but without any strict frames and promises - some blocker might happen.

**Comment by provegard** [comment]
Thanks @erik-bershel, good to know!

**Comment by hudsy13** [comment]
Hello @erik-bershel any update on when a new 2022 runner will be released.  I am encountering the same issue with the missing ATL and deciding on whether to add the code or wait for the next runner.

Thanks

**Comment by erik-bershel** [comment]
Hey @hudsy13!
Suddenly we got some release blocker. But we are keeping hope to release Windows images ob this week.

**Comment by bhanusridhar** [comment]
Hi @erik-bershel,
We are having our pipelines running on windows-latest image. With latest image version 20240514.3.0, we are facing issue in VSBuild task as "Error RC1015: cannot open include file 'afxres.h'".

With latest version of windows-2019 image, VSBuild task is working fine.

Will this issue also be fixed as part of the deployment.

Please feel to correct me if I am writing down in the wrong window.

**Comment by erik-bershel** [comment]
Hey @bhanusridhar!
It seems to be a part of v142 MFC VC component which was previously removed. I'll take a look on what might be done here to eliminate this. Till possible solution it's better to install it in runtime.

**Comment by bhanusridhar** [comment]
@erik-bershel  As it we working on windows-2019 image, currently mapped our pipeline to work on it without making any additional changes of including any installation steps.

Hoping to see it work in windows-2022 image as well.
Thanks in advance!

**Comment by erik-bershel** [comment]
Hey @bhanusridhar!
I'm a bit surprised. Header file `afxres.h` supposed to be a part of `Microsoft.VisualStudio.Component.VC.ATLMFC` which is already a part of our installation.

And it seems to be existing on disk:

```text
Run Get-ChildItem -Path "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\" -Recurse -Filter "afxres.h" | Select-Object -ExpandProperty FullName
C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.39.33519\atlmfc\include\afxres.h
```

May I ask you run once next code before build to check if the issue persists with the current version of library only?

```yml
      - name: Delete components
        run: |
                Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
                $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
                $componentsToRemove= @(
                    "Microsoft.VisualStudio.Component.VC.ATLMFC"
                    "Microsoft.VisualStudio.Component.VC.ATLMFC.Spectre"                   
                )
                [string]$workloadArgs = $componentsToRemove | ForEach-Object {" --remove " +  $_}
                $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
                # should be run twice
                $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
                $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
      
      - name: Install components
        run: |
                Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
                $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
                $componentsToRemove= @(
                  "Microsoft.VisualStudio.Component.VC.14.29.16.11.MFC"
                  "Microsoft.VisualStudio.Component.VC.14.29.16.11.MFC.Spectre"
                  "Microsoft.VisualStudio.Component.VC.14.29.16.11.ATL"
                  "Microsoft.VisualStudio.Component.VC.14.29.16.11.ATL.Spectre"
                )
                [string]$workloadArgs = $componentsToRemove | ForEach-Object {" --add " +  $_}
                $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
                # should be run twice
                $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
                $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
```

**Comment by bhanusridhar** [comment]
Hi @erik-bershel. I have tested the above.
By including the above scripts before build, Build solution passed now.

So, I guess issue persists with the current version of library only.

**Comment by bhanusridhar** [comment]
Any update here please @erik-bershel

**Comment by erik-bershel** [comment]
Hey @bhanusridhar!
Image rollout is in progress. Might be fixed with the update - it has major build tools update. In other case should be raised to the Microsoft Support via Developer Community: https://developercommunity.microsoft.com/VisualStudio

**Comment by hudsy13** [comment]
Hi @erik-bershel  thanks for the updates.  The image rollout that is currently in progress is that to correct the atlbase.h missing issue or one of the others that have been raised in this thread?

I just attempted to run our pipeline again (image '20240603.1.0') and it's still throwing an error, so I was looking for clarification.

Thanks

**Comment by erik-bershel** [comment]
Hey @hudsy13!
Which issue do we speak about? I'm a bit confused here with all other issues. 😄 
For the very first mentioned `altbase.h` it should be resolved in the upcoming release (except the small possibility that the latest build tools update was broken). For the `afxres.h` it's only workaround available - this one not linked somehow and it seems like a VS component bug.

**Comment by erik-bershel** [comment]
Lets see.

Issue firstly happen to be when we removed v142 and other components. `atlbase.h` is supposed to be a part of "Microsoft.VisualStudio.Component.VC.ATL" which was directly installed by https://github.com/actions/runner-images/pull/9876/files. I was expecting [20240603](https://github.com/actions/runner-images/pull/9990) release to solve the initial issue.

Judging by your previous comment, the update did not solve the problem. In this case, it is a bug of the component itself. As a temporary workaround, you can downgrade it in runtime or contact the Visual Studio developers - unfortunately, we are not yet able to install two versions of components at the same time due to a bug.

To check it before reporting I may recommend you to run code from this comment: https://github.com/actions/runner-images/issues/9873#issuecomment-2116034596. In case it works for you - it's for sure a bug of VS2022.

**Comment by sodul** [comment]
@erik-bershel We tried to rollback the ATL re-install logic a few minutes ago and unfortunately we are getting the `fatal error C1083: Cannot open include file: 'atlbase.h': No such file or directory` error.

Here is the output from the setup step:
```
Current runner version: '2.317.0'
Operating System
  Microsoft Windows Server 2022
  10.0.20348
  Datacenter
Runner Image
  Image: windows-2022
  Version: 20240603.1.0
  Included Software: https://github.com/actions/runner-images/blob/win22/20240603.1/images/windows/Windows2022-Readme.md
  Image Release: https://github.com/actions/runner-images/releases/tag/win22%2F20240603.1
Runner Image Provisioner
  2.0.370.1
GITHUB_TOKEN Permissions
Secret source: Actions
Prepare workflow directory
Prepare all required actions
Getting action download info
Download action repository 'actions/checkout@v4' (SHA:a5ac7e51b41094c92402da3b24376905380afc29)
Download action repository 'microsoft/setup-msbuild@v2' (SHA:6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce)
Download action repository 'darenm/Setup-VSTest@v1.2' (SHA:d9a5dffa3f11d9c27ec42eb69515d3aaeaad9ef8)
Download action repository 'actions/setup-python@v5' (SHA:82c7e631bb3cdc910f68e0081d67478d79c6982d)
Download action repository 'actions/upload-artifact@v4' (SHA:65462800fd760344b1a7b4382951275a0abb4808)
Complete job name: CI-checks
```

The workaround to uninstall and re-install ATL still works, but it takes an extra 7m to do that each time.

**Comment by bhanusridhar** [comment]
> Hey @bhanusridhar! Image rollout is in progress. Might be fixed with the update - it has major build tools update. In other case should be raised to the Microsoft Support via Developer Community: https://developercommunity.microsoft.com/VisualStudio

Seems 20240603 image didn't fixed. May be I should approach Developer community. Thanks for the help in providing workaround. Anyhow, we are using windows-2019.

**Comment by erik-bershel** [comment]
Hey @sodul and @bhanusridhar!
Major VC components update happened last week. It gave rise to many incompatibility problems and, as a result, it is now very difficult to understand anything. I would prefer to continue to deal with the problem on our side, but a little later. Presumably over the next couple of weeks the main problems with the `windows-2022` image should be fixed, after which we will again be able to experiment with a set of libraries. I still hope that we can make a set in such a way that it can be added to the image without compromising other builds.
But I will also be very grateful to you for sending a report to the developers - perhaps they know the problem and they will be able to offer an optimal solution faster.

**Comment by sodul** [comment]
@erik-bershel where should we send a report? I'm happy to send one but I'm not sure which developers to ping.

**Comment by erik-bershel** [comment]
@sodul I recommend reporting the bug to the [Visual Studio Developer Community](https://developercommunity.visualstudio.com/index.html/report)

**Comment by hudsy13** [comment]
Still experiencing issues with our build failing via ADO pipelines using windows-2022 and visual studio 2022 due to the missing atlbase.h file.

I have tried the workaround but it doesn't appear to be doing anything (just sits there until pipeline times out).

Is that suppose to be a powershell script?

**Comment by erik-bershel** [comment]
Hey @hudsy13!
I'm not sure about workaround now. Last VS update changed plenty of things. @sodul reported previously that it stopped working. I made a small update (might help if one of the relevant packages contain required headers, but no promises).

If you are using Azure Pipelines might worth trying adding the next steps into build job:

```yml
  steps:
  - task: PowerShell@2
    displayName: Delete components
    inputs:
      targetType: 'inline'
      script: |
        Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
        $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
        $componentsToRemove= @(
            "Microsoft.VisualStudio.Component.VC.ATL"
        )
        [string]$workloadArgs = $componentsToRemove | ForEach-Object {" --remove " +  $_}
        $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
        # should be run twice
        $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
        $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden

  - task: PowerShell@2
    displayName: Install components
    inputs:
      targetType: 'inline'
      script: |
        Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
        $InstallPath = "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
        $componentsToRemove= @(
          "Microsoft.VisualStudio.Component.VC.v141.ATL"
          "Microsoft.VisualStudio.Component.VC.v141.ATL.ARM"
          "Microsoft.VisualStudio.Component.VC.v141.ATL.ARM64"
        )
        [string]$workloadArgs = $componentsToRemove | ForEach-Object {" --add " +  $_}
        $Arguments = ('/c', "vs_installer.exe", 'modify', '--installPath', "`"$InstallPath`"",$workloadArgs, '--quiet', '--norestart', '--nocache')
        # should be run twice
        $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
        $process = Start-Process -FilePath cmd.exe -ArgumentList $Arguments -Wait -PassThru -WindowStyle Hidden
```

**Comment by hudsy13** [comment]
@erik-bershel thanks for the updated workaround, this one worked and allowed the build to be successful on windows-2022 runners albeit it did add 13 minutes onto the build process (9m to delete components and 4m to add).  However, it is at least building again.  Thanks.  Hopefully the permanent fix will be out soon.

**Comment by erik-bershel** [comment]
@hudsy13 try removing the deletion step, it was necessary because previously there was sometimes a bug with library compatibility - perhaps no longer relevant due to the latest updates. Since now we are sure that the workround itself is working, we can check it without deleting it. If it continues to work, then consider that you will save yourself minutes on reconfiguration.

**Comment by erik-bershel** [comment]
If the developers ignore the report or are unable to provide solutions or a more optimal workround, then we will think about adding older versions of the components.

**Comment by kanak-clumio** [comment]
@erik-bershel I've submitted feedback to Visual Studio by following steps mentioned here - [Visual Studio Developer Community](https://developercommunity.visualstudio.com/index.html/report) 10 days back but I've not heard back from them yet.

**Comment by tmp64** [comment]
If you use [lukka/run-cmake](https://github.com/lukka/run-cmake), this error may be caused by vcpkg using v142 toolset instead of v143. [MS started to use 14.4x version range for v143](https://devblogs.microsoft.com/cppblog/msvc-toolset-minor-version-number-14-40-in-vs-2022-v17-10/), which broke compiler detection code. You need to update vcpkg baseline to the latest one to fix it.

**Comment by erik-bershel** [comment]
Hey @kanak-clumio!

> @erik-bershel I've submitted feedback to Visual Studio by following steps mentioned here - [Visual Studio Developer Community](https://developercommunity.visualstudio.com/index.html/report) 10 days back but I've not heard back from them yet.

It seems they are waiting for your response. Check [here](https://developercommunity.microsoft.com/t/Missing-VC-components-with-windows-2022/10679957?q=fatal+error+C1083%3A+Cannot+open+include+file%3A+%27atlbase.h%27%3A+No+such+file+or+directory&sort=newest&fTime=6m&ftype=problem&stateGroup=active&page=13).

Unfortunately, we decided to close this issue for a number of reasons:
- the problem itself lies outside the image, the necessary components are installed on the disk
- a working workround was provided
- we would not like to deviate from our current policy of supporting Visual Studio 2022 components towards more complex solutions - unfortunately, this often only leads to bigger problems.

In order to make a “cheaper” workaround, I recommend trying to re-register existing files. The biggest problem in this case will be building the path to the file dynamically, but in general this is a solvable problem.

**Comment by h-vetinari** [comment]
The developer community [issue](https://developercommunity.microsoft.com/t/Missing-VC-components-with-windows-2022/10679957?q=fatal+error+C1083%3A+Cannot+open+include+file%3A+%27atlbase.h%27%3A+No+such+file+or+directory&sort=newest&fTime=6m&ftype=problem&stateGroup=active&page=13) was closed with exactly the same work-around as this issue, which is no help at all. Could you please figure out whose responsibility it is and come up with an approach to fix it together?

In the meantime, this issue should be reopened.

**Comment by sodul** [comment]
I would add that the feedback from Microsoft was to make config changes through the Windows UI, even though the issue was specifically mentioning GitHub pipelines. It seems like an issue where the left hand is not talking with the right hand and the final customer is in between. Since GitHub is owned by Microsoft I consider this to be 100% a Microsoft regression that Microsoft and its subsidiaries need to resolve for their paying customers.

**Comment by Metadorius** [comment]
Apparently this bug is still here: https://github.com/CnCNet/yrpp-spawner/actions/runs/13531026351/job/37813576891
Please reopen the issue.

**Comment by hudsy13** [comment]
The workaround previously mentioned is good for a stop gap measure.  It adds quite a bit of time to the pipeline run as it takes quite a while to remove/re-install the components.

**Comment by Avasam** [comment]
I slightly modified the above proposed workaround to the bare minimum install I needed, avoid `cmd`, and a few additional styling adjustments:
https://github.com/Avasam/pywin32/commit/711ddb1527a5ff3a87ced4393a355abd92df8c48#diff-7829468e86c1cc5d5133195b5cb48e1ff6c75e3e9203777f6b2e379d9e4882b3R65-R82

```yaml
      - name: Install missing Visual Studio components
        run: |
          Set-Location "C:\Program Files (x86)\Microsoft Visual Studio\Installer\"
          $VsInstallPath = vswhere.exe -latest -products * -requires Microsoft.Component.MSBuild -property installationPath
          [string]$ComponentsToAdd = @(
            "Microsoft.VisualStudio.Component.VC.14.29.16.11.ATL" # for windows-2022
            "Microsoft.VisualStudio.Component.VC.14.29.16.11.ATL.ARM64" # for windows-11-arm
          ) | ForEach-Object {"--add $_"}
          $ArgumentList = ('modify', '--installPath', "`"$VsInstallPath`"", $ComponentsToAdd, '--quiet', '--norestart', '--nocache')
          echo "vs_installer.exe $($ArgumentList -join ' ')"
          # should be run twice for some reason
          Start-Process -FilePath vs_installer.exe -ArgumentList $ArgumentList -Wait -PassThru -WindowStyle Hidden
          Start-Process -FilePath vs_installer.exe -ArgumentList $ArgumentList -Wait -PassThru -WindowStyle Hidden
```

After experimenting, I found that I didn't need to first remove the components. (same speed to remove + install than it is to just call install)
I also found that the exact MSVC + VS version combo of `14.29`&`16.11` is also what I need, despite `vswhere.exe -latest` giving me different results.

Adding ~8-12 minutes to every CI run isn't great. I also don't understand why we need to run the installation twice.

**Comment by Avasam** [comment]
Why does vs_installer need to be run twice? And is there anyway to cache this installation across runs? Taking an extra ~8-12 minutes per job is really awful.

**Comment by KerstinKeller** [comment]
We just stumbled onto this issue, because of the deprecation of the windows-2019 runners and the need to upgrade to 2022 oder 2025 runners.
Hitting the same problem. Would be great if those headers were available from the start, without the need to reinstall anything.

**Comment by Starkku** [comment]
Likewise now having trouble with this due to deprecation of `windows-2019`. The workaround is not acceptable due to the steep amount of extra time it adds to the workflows.

**Comment by Avasam** [comment]
Additional issue with the provided workaround:
Neither `Microsoft.VisualStudio.Component.VC.14.29.16.11.ATL` nor `Microsoft.VisualStudio.Component.VC.14.29.16.11.ATL.ARM64` seem to work for the `windows-11-arm` runner. Back to having `fatal error C1083: Cannot open include file: 'atlbase.h': No such file or directory` on there: https://github.com/mhammond/pywin32/actions/runs/16503124706/job/46666815444?pr=2581#step:10:101
